### PR TITLE
actions/wake: add github action to run wake in the environment

### PR DESCRIPTION
**Pull request by terpstra**
This PR:
- defines a github action to run wake in the envinronment-blockci-sifive docker image
- adds documentation for said action
- test that action as part of CI for this repository

Example:
```yaml
 jobs:
   test:
     name: Scala compile
     runs-on: ubuntu-latest

     steps:
     - name: Wit Init
       uses: sifive/wit/actions/init@v0.13.2
       with:
         additional_packages: git@github.com:sifive/environment-blockci-sifive.git::0.7.0

     - name: Run wake scala compile
       uses: sifive/environment-blockci-sifive/actions/wake@0.7.0
       with:
         command: -x 'compileScalaModule myScalaModule | getPathResult'
 ```

### CODE REVIEW

**Review by richardxia — APPROVED** [review]
LGTM!

**Comment by terpstra** [comment]
@richardxia I'd appreciate a re-review given the changes. Once merged, please also advance the 0.7.0 tag to the merge commit.

**Review by richardxia — APPROVED** [review]
LGTM!

**Comment by richardxia** [comment]
Actually, let me push up some release notes.

**Pull request merged**
